# Generated by Django 4.0.1 on 2022-10-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='file')),
                ('type', models.CharField(choices=[('PHO', 'Image'), ('VID', 'Video')], max_length=4, verbose_name='type')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'multimedias',
                'db_table': 'medias',
            },
        ),
    ]
