# Generated by Django 4.0.1 on 2022-12-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('PHOTO', 'Image'), ('VIDEO', 'Video')], max_length=8, verbose_name='type'),
        ),
    ]
