# Generated by Django 4.0.1 on 2022-10-02 17:12

import back.apps.vehicle.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('year', models.IntegerField(validators=[back.apps.vehicle.models.min_valid_year, back.apps.vehicle.models.max_valid_year], verbose_name='year')),
                ('type', models.CharField(choices=[('HB', 'Hatchback'), ('SDN', 'Sedan'), ('PU', 'Pickup truck'), ('JEEP', 'Jeep'), ('SSUV', 'Small SUV'), ('MSUV', 'Mid-size SUV'), ('LSUV', 'Full-size SUV'), ('SW', 'Station wagon')], max_length=4, verbose_name='type')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicles',
                'unique_together': {('brand', 'model', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VehiclePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('currency', models.CharField(default='USD', max_length=12, verbose_name='currency')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price')),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='rental price')),
                ('sale_type', models.CharField(choices=[('RENT', 'Rental'), ('SALE', 'Sale'), ('BOTH', 'Rental and sale')], max_length=4, verbose_name='sale type')),
                ('accesories', models.TextField(verbose_name='accesories')),
                ('services', models.TextField(verbose_name='services')),
                ('vehicle_state', models.CharField(choices=[('NEW', 'new'), ('USED', 'used')], max_length=4, verbose_name='vehicle state')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='vehicle.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle post',
                'verbose_name_plural': 'Vehicle posts',
                'db_table': 'vehicle_posts',
            },
            bases=('post.post',),
        ),
    ]
