# Generated by Django 4.0.1 on 2022-09-28 00:41

import back.apps.vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('year', models.IntegerField(validators=[back.apps.vehicle.models.min_valid_year, back.apps.vehicle.models.max_valid_year], verbose_name='year')),
                ('type', models.CharField(choices=[('HB', 'Hatchback'), ('SDN', 'Sedan'), ('PU', 'Pickup truck'), ('JEEP', 'Jeep'), ('SSUV', 'Small SUV'), ('MSUV', 'Mid-size SUV'), ('LSUV', 'Full-size SUV'), ('SW', 'Station wagon')], max_length=4, verbose_name='type')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicles',
                'unique_together': {('brand', 'model', 'year')},
            },
        ),
    ]
