# Generated by Django 4.0.1 on 2022-10-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('HB', 'Hatchback'), ('SDN', 'Sedan'), ('PU', 'Pickup truck'), ('JEEP', 'Jeep'), ('SSUV', 'Small SUV'), ('MSUV', 'Mid-size SUV'), ('LSUV', 'Full-size SUV'), ('SW', 'Station wagon')], max_length=4, null=True, verbose_name='type'),
        ),
    ]
