# Generated by Django 4.0.1 on 2022-11-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emaildevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutwebsite',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='other method'),
        ),
        migrations.AlterField(
            model_name='notificationmethod',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='other method'),
        ),
    ]
