# Generated by Django 4.0.1 on 2022-11-11 04:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_aboutwebsite_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmethod',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='send notification'),
        ),
        migrations.AlterField(
            model_name='notificationmethod',
            name='facebook',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='facebook mail'),
        ),
        migrations.AlterField(
            model_name='notificationmethod',
            name='sms',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='text message'),
        ),
    ]
