# Generated by Django 4.0.1 on 2022-09-28 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('address', '0001_initial'),
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='send notification')),
                ('sms', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='text message')),
                ('other', models.TextField(verbose_name='other method')),
                ('facebook', models.EmailField(max_length=254, verbose_name='facebook mail')),
            ],
            options={
                'verbose_name': 'notification method',
                'verbose_name_plural': 'notification methods',
                'db_table': 'notification_methods',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='charge',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'English')], default='ES', max_length=4, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('notification_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='user.notificationmethod', verbose_name='notification method')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to='social.social', verbose_name='social')),
            ],
            options={
                'verbose_name': 'user social',
                'verbose_name_plural': 'user socials',
                'db_table': 'user_socials',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_bank', models.CharField(max_length=512, verbose_name='source bank')),
                ('target_bank', models.CharField(max_length=512, verbose_name='target bank')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='address.country', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'payment info',
                'verbose_name_plural': 'payment infos',
                'db_table': 'payment_info',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='send notification')),
                ('frecuency', models.CharField(max_length=255, verbose_name='frecuency')),
                ('notification_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='user.notificationmethod', verbose_name='notification methods')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification setting',
                'verbose_name_plural': 'notification settings',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='AboutWebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.BooleanField(verbose_name='web')),
                ('friends', models.BooleanField(verbose_name='friends')),
                ('other', models.TextField(verbose_name='other method')),
                ('socials', models.ManyToManyField(related_name='+', to='social.Social', verbose_name='social')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_website', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'about website',
                'verbose_name_plural': 'abouts website',
                'db_table': 'about_website',
            },
        ),
    ]
