# Generated by Django 4.0.1 on 2022-11-11 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('user', '0004_alter_notificationmethod_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocial',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to='social.social', verbose_name='social'),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='value'),
        ),
    ]
