# Generated by Django 4.0.1 on 2022-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service'),
        ('user', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(related_name='+', to='service.Service', verbose_name='service preferences'),
        ),
    ]
