# Generated by Django 4.0.1 on 2022-10-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Profession name')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'db_table': 'professions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('schedule', models.CharField(max_length=180, verbose_name='schedule')),
                ('interactors', models.ManyToManyField(related_name='+', to='job.Profession')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job.contractmodality', verbose_name='contact modality')),
                ('supervisors', models.ManyToManyField(related_name='+', to='job.Profession')),
            ],
            options={
                'verbose_name': 'Job post',
                'verbose_name_plural': 'Job posts',
                'db_table': 'job_posts',
            },
            bases=('post.post',),
        ),
    ]
