# Generated by Django 4.0.1 on 2022-10-02 17:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('local_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='local phone')),
            ],
            options={
                'verbose_name': 'representant',
                'verbose_name_plural': 'representants',
                'db_table': 'representants',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('tax_id', models.CharField(max_length=255, verbose_name='tax id')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='address.address', verbose_name='address')),
                ('representant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business.representant', verbose_name='representant')),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'db_table': 'businesses',
            },
        ),
    ]
