# Generated by Django 4.0.1 on 2022-12-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tax_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='tax id'),
        ),
    ]
