# Generated by Django 4.0.1 on 2022-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Phone code'),
        ),
    ]
