# Generated by Django 4.0.1 on 2022-12-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('full_name', models.CharField(max_length=255, verbose_name='client full name')),
                ('reason', models.CharField(max_length=255, verbose_name='contact reason')),
                ('body', models.TextField(verbose_name='contact body')),
            ],
            options={
                'verbose_name': 'contact me submission',
                'verbose_name_plural': 'contact me submissions',
                'db_table': 'contact_me_submissions',
            },
        ),
    ]
