# Generated by Django 4.0.1 on 2022-12-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='body',
        ),
    ]
