# Generated by Django 4.0.1 on 2022-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_pagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetting',
            name='first_name',
            field=models.CharField(default='Vittorio', max_length=128, verbose_name='owner first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='last_name',
            field=models.CharField(default='Adesso', max_length=128, verbose_name='owner last name'),
            preserve_default=False,
        ),
    ]
