# Generated by Django 4.0.1 on 2022-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_pagesetting_first_name_pagesetting_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetting',
            name='bank_detail',
            field=models.JSONField(default={'jaja': 'jiji'}, verbose_name='bank detail'),
            preserve_default=False,
        ),
    ]
