# Generated by Django 4.0.1 on 2022-10-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'Service post',
                'verbose_name_plural': 'Service posts',
                'db_table': 'service_posts',
            },
            bases=('post.post',),
        ),
    ]
