# Generated by Django 4.0.1 on 2022-10-02 17:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('local_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='local phone')),
                ('contact_hour_start', models.DateTimeField(verbose_name='hour start')),
                ('contact_hour_end', models.DateTimeField(verbose_name='hour end')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='json data for contact')),
            ],
            options={
                'verbose_name': 'contact seller',
                'verbose_name_plural': 'contact sellers',
                'db_table': 'contact_sellers',
            },
        ),
        migrations.CreateModel(
            name='DayOption',
            fields=[
                ('option', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='option')),
            ],
            options={
                'verbose_name': 'day option',
                'verbose_name_plural': 'day options',
                'db_table': 'day_options',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='details')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date updated')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='address.address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'posts',
                'ordering': ('date_updated',),
            },
        ),
    ]
