# Generated by Django 4.0.1 on 2022-10-02 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.contact', verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='media.Media'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_days',
            field=models.ManyToManyField(to='post.DayOption'),
        ),
    ]
