# Generated by Django 4.0.1 on 2022-12-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='media',
        ),
    ]
