# Generated by Django 4.0.1 on 2022-12-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_images_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.contact', verbose_name='contact'),
        ),
    ]
