# Generated by Django 4.0.1 on 2022-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_type'),
        ('post', '0004_alter_post_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(blank=True, to='media.Media'),
        ),
    ]
