# Generated by Django 4.0.1 on 2022-12-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_media_type'),
        ('post', '0005_alter_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='+', to='media.Media', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='+', to='media.Media', verbose_name='videos'),
        ),
    ]
